[build-system]
requires = ["setuptools", "setuptools-scm", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "spacetimedb_python_sdk"
authors = [
    {name = "Derek Brinkmann", email = "derek@clockworklabs.io"},
]
long_description = """
# SpaceTimeDB Python SDK
The SpacetimeDB Python SDK is a software development kit (SDK) designed to simplify the interaction with SpacetimeDB server modules.
"""
long_description_content_type = "text/markdown"

dependencies = [
    "websocket-client",
    "configparser",
]
dynamic = ["version"]

# pyproject.toml
[tool.setuptools_scm]
write_to = "src/spacetimedb_python_sdk/_version.py"