# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from typing import List

class Point:
	is_table_class = False

	def __init__(self, data: List[object]):
		self.data = {}
		self.data["x"] = int(data[0])
		self.data["y"] = int(data[1])

	def encode(self) -> List[object]:
		return [self.x, self.y]

	def __getattr__(self, name: str):
		return self.data.get(name)
